//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_kursovaya_wpf.AppDataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gibddEntities1 : DbContext
    {
        private static gibddEntities1 _context;
        public gibddEntities1()
            : base("name=gibddEntities1")
        {
        }
        public static gibddEntities1 GetContext()
        {
            if (_context == null)
                _context = new gibddEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sotrudniki> sotrudniki { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<type_of_transport> type_of_transport { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
