//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_kursovaya_wpf.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sotrudniki()
        {
            this.transport = new HashSet<transport>();
        }
    
        public int id_sotrudnik { get; set; }
        public Nullable<int> age { get; set; }
        public string dolzhnost { get; set; }
        public string name { get; set; }
        public string zvanie { get; set; }
        public string contact { get; set; }
        public string adres { get; set; }
        public string otdel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transport> transport { get; set; }
    }
}
